name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Build and Package Bundle
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          ./gradlew zipBundle -Pversion="${TAG_VERSION}"
        working-directory: expressj
        env:
          CI: "true"
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload to Sonatype Central Portal
        run: |
          echo "${{ secrets.MAVEN_USERNAME }}:${{ secrets.MAVEN_PASSWORD }}" | base64 > auth.txt
          curl --request POST \
            --verbose \
            --fail \
            --header "Authorization: Basic $(cat auth.txt)" \
            --form "bundle=@core/build/bundle.zip" \
            --url "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC"
          rm auth.txt
        working-directory: expressj
